apiVersion: apps/v1
kind: Deployment
metadata:
  name: "springbootserver"
  labels:
    app: "springbootserver"
spec:
  selector:
    matchLabels:
      app: springbootserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "springbootserver"
    spec:
      containers:
        - name: springbootserver
          image: "mwacha/hello-springboot:v6.3"
          envFrom:
            - configMapRef:
                name: springbootserver-env
            - secretRef:
                name: springbootserver-secret
          volumeMounts: # monta o o volume config(declarado abaixo) dentro da aplicação
            - mountPath: "/java/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family # nome do configmap-family
            items:
            - key: members # dados que estão no configmap-family
              path: "family.txt"
