apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springbootserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootserver
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25